## Hotel Data Dashboard
## DSCI 532
## Group 20
## 2021/01/19

## This makefile will download and preprocess data for visualization dashboard


all : data/raw/hotels2.csv

# Get raw hotel data from web
data/raw/hotels2.csv : src/download_data.py
	python src/download_data.py 'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv data/raw/hotels2.csv' data/raw/hotels2.csv

# Get country cod data from web
data/raw/hotels2.csv : src/download_data.py
	python src/download_data.py 'https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv' data/raw/country_codes.csv


# # Rename columns, remove unused columns
# data/processed/clean_hotels.csv : data/raw/hotels.csv
# 	python src/clean_data.py

clean :
	rm -f data/raw/hotels2.csv
	
